# Generated by Django 5.2.17 on 2026-08-05 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('documentation', 'Documentation'), ('qa', 'QA'), ('lattice', 'Lattice'), ('safety', 'Safety'), ('maintenance', 'Maintenance'), ('design', 'Design'), ('status', 'Status'), ('other', 'Other')], default='other', max_length=32)),
                ('handler', models.CharField(blank=True, choices=[('', 'None'), ('pdmlink', 'PDMLink'), ('component_design', 'Component Design'), ('traveler_template', 'Traveler Template'), ('traveler_instance', 'Traveler Instance'), ('document', 'Document'), ('image', 'Image'), ('http_link', 'HTTP Link'), ('currency', 'Currency'), ('boolean', 'Boolean'), ('date', 'Date')], default='', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('default_units', models.CharField(blank=True, max_length=64)),
                ('default_value', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('group_writeable', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('alternate_name', models.CharField(blank=True, max_length=256)),
                ('model_number', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('project', models.CharField(blank=True, default='ePIC', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('group_writeable', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=128)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='cdb.component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['component', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('group_writeable', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('project', models.CharField(blank=True, default='ePIC', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesignElement',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('element_name', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('child_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_elements', to='cdb.design')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_memberships', to='cdb.component')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='cdb.design')),
            ],
            options={
                'ordering': ['element_name'],
                'unique_together': {('design', 'element_name')},
            },
        ),
        migrations.CreateModel(
            name='DesignElementInstance',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_instances', to='cdb.designelement')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_installations', to='cdb.componentinstance', unique=True)),
            ],
            options={
                'ordering': ['instance__tag'],
            },
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('group_writeable', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('project', models.CharField(blank=True, default='ePIC', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='design',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this design was instantiated from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='cdb.designtemplate'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('location_type', models.CharField(choices=[('building', 'Building'), ('room', 'Room'), ('cabinet', 'Cabinet'), ('shelf', 'Shelf'), ('other', 'Other')], default='room', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='cdb.institution')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cdb.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='design',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Where this design is being assembled. A design lives in exactly one place, so placeholder replacement offers only inventory instances stored at this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='cdb.location'),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='cdb.location'),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, choices=[('', 'General'), ('installation', 'Installation'), ('inventory', 'Inventory'), ('design', 'Design'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('decommission', 'Decommission'), ('other', 'Other')], default='', max_length=32)),
                ('entry', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='log_attachments/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='cdb.component')),
                ('component_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='cdb.componentinstance')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='cdb.design')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdb_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=128)),
                ('value', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='property_files/')),
                ('units', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_dynamic', models.BooleanField(default=False)),
                ('user_writable', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='cdb.component')),
                ('component_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='cdb.componentinstance')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='cdb.design')),
                ('design_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='cdb.designelement')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb.propertytype')),
            ],
            options={
                'ordering': ['property_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentSource',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('part_number', models.CharField(blank=True, max_length=128)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('manufacturer', 'Manufacturer'), ('both', 'Vendor & Manufacturer')], default='vendor', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb.component')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdb.source')),
            ],
            options={
                'unique_together': {('component', 'source')},
            },
        ),
        migrations.AddField(
            model_name='component',
            name='sources',
            field=models.ManyToManyField(blank=True, through='cdb.ComponentSource', to='cdb.source'),
        ),
        migrations.CreateModel(
            name='TechnicalSystem',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(blank=True, help_text='Django auth Group responsible for this technical system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_systems', to='auth.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='technical_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_instances', to='cdb.technicalsystem'),
        ),
        migrations.AddField(
            model_name='component',
            name='technical_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='cdb.technicalsystem'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='cdb.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignTemplateElement',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('element_name', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_memberships', to='cdb.component')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='cdb.designtemplate')),
            ],
            options={
                'ordering': ['element_name'],
                'unique_together': {('template', 'element_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('name', 'project')},
        ),
    ]
