# Generated by Django 5.2.17 on 2026-08-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hdb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="designtemplate",
            name="product_component",
            field=models.ForeignKey(
                blank=True,
                help_text="Catalog Component representing one built/assembled instance of this template -- e.g. the 'BTOF Stavelet' template's product_component is the 'BTOF Stavelet' Component, so a physically completed stavelet can be tracked as a ComponentInstance like any other part. Independent of nesting: set this whether or not this template is ALSO used as another template's child_template placeholder -- the two are unrelated concerns (one is 'what do I contain', the other is 'what am I, once built').",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_of_templates",
                to="hdb.component",
            ),
        ),
        migrations.AddField(
            model_name="designtemplateelement",
            name="child_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Nested sub-template placeholder, e.g. a Stave's element pointing at the Half-Stave template. PROTECTed rather than SET_NULL: deleting it out from under a placeholder that's set to exactly-one-of-component/child_template would leave neither set. Delete the placeholder (or repoint it) first, then the template.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parent_elements",
                to="hdb.designtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="designtemplateelement",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_memberships",
                to="hdb.component",
            ),
        ),
        migrations.AddConstraint(
            model_name="designtemplateelement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("child_template__isnull", True), ("component__isnull", False)
                    ),
                    models.Q(
                        ("child_template__isnull", False), ("component__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="designtemplateelement_exactly_one_of_component_or_child_template",
            ),
        ),
    ]
