# Generated by Django 5.2.17 on 2026-08-27 01:32

import django.db.models.deletion
from django.db import migrations, models


def _backfill_child_template_name(apps, schema_editor):
    """Populate child_template_name for every pre-existing template-type
    placeholder from its already-resolved child_template.name, before the
    new exactly-one-of constraint (which requires child_template_name to
    be set whenever child_template is) goes on. Every row that predates
    this migration was resolved eagerly at upload time -- there's no
    pre-existing "pending" state to account for here, only ordinary
    already-linked placeholders."""
    DesignTemplateElement = apps.get_model("hdb", "DesignTemplateElement")
    for element in DesignTemplateElement.objects.filter(child_template__isnull=False):
        element.child_template_name = element.child_template.name
        element.save(update_fields=["child_template_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("hdb", "0002_designtemplate_nested_child_template"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="designtemplateelement",
            name="designtemplateelement_exactly_one_of_component_or_child_template",
        ),
        migrations.AddField(
            model_name="designtemplateelement",
            name="child_template_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="For a template-type placeholder, the child_template's name as given in the uploaded YAML -- always populated for that placeholder shape, whether or not child_template has resolved yet. YAML uploads are asynchronous and order-independent: a parent template can be uploaded before the sub-template it names exists. When it names a template that isn't in the database yet, child_template stays NULL and this field records the intent; resolve_pending_template_references() re-attempts the link (with the same cycle/project/owner_group validation as an eagerly-resolved reference) after every YAML upload, so upload order never matters. See DesignTemplate.is_complete()/pending_placeholders() for the reader-facing view of what's still outstanding. Left blank for a component-type placeholder.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="designtemplateelement",
            name="child_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Nested sub-template placeholder, e.g. a Stave's element pointing at the Half-Stave template. Left NULL while child_template_name hasn't resolved yet -- see that field and resolve_pending_template_references(). PROTECTed rather than SET_NULL once resolved: deleting it out from under a placeholder that's set to exactly-one-of-component/child_template would leave neither set. Delete the placeholder (or repoint it) first, then the template.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parent_elements",
                to="hdb.designtemplate",
            ),
        ),
        migrations.RunPython(_backfill_child_template_name, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="designtemplateelement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("child_template__isnull", True),
                        ("child_template_name", ""),
                        ("component__isnull", False),
                    ),
                    models.Q(
                        ("component__isnull", True),
                        models.Q(("child_template_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="designtemplateelement_exactly_one_of_component_or_child_template",
            ),
        ),
    ]
