# Generated by Django 6.0.8 on 2026-08-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdb', '0004_template_source_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtemplate',
            name='source_git_commit',
            field=models.CharField(blank=True, default='', help_text="`git rev-parse HEAD` of the repository containing source_path, captured at load time on a best-effort basis (blank if the file isn't inside a git checkout, or git isn't available). Describes the repo state the load was run from -- NOT a guarantee source_path itself was committed at that commit; a dirty working tree at load time still records HEAD, so treat this as 'roughly when/where', not as a cryptographic proof by itself -- source_sha256 is the one that's exact.", max_length=40),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='source_path',
            field=models.CharField(blank=True, default='', help_text='Path to the YAML file this template was last loaded from, as given to load-template (relative to the repo root when the file is inside a git checkout, otherwise as passed).', max_length=512),
        ),
        migrations.AlterField(
            model_name='designtemplate',
            name='source_sha256',
            field=models.CharField(blank=True, default='', help_text="SHA-256 of source_path's exact file content at the time of the most recent load. Compared against the file's current hash by `hdb verify-template` to tell 'file changed since last load' apart from 'database was edited some other way'.", max_length=64),
        ),
    ]
