# Generated by Django 6.0.8 on 2026-09-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdb', '0005_alter_designtemplate_source_git_commit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='hdb.location'),
        ),
        migrations.AlterField(
            model_name='design',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Where this design is being assembled. A design lives in exactly one place, so placeholder replacement offers only inventory instances stored at this location.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='hdb.location'),
        ),
    ]
